# Generated by Django 5.1.5 on 2025-01-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('department_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufcmsdb.department')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('module', models.CharField(max_length=80)),
            ],
            options={
                'unique_together': {('action', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('permissions', models.ManyToManyField(related_name='roles', to='ufcmsdb.permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('cnicno', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufcmsdb.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufcmsdb.designation')),
                ('roles', models.ManyToManyField(related_name='users', to='ufcmsdb.role')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('expense_slip', models.ImageField(blank=True, null=True, upload_to='expense_slips/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufcmsdb.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufcmsdb.user')),
            ],
        ),
    ]
