# Generated by Django 5.1.5 on 2025-01-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='cnicno',
            field=models.BigIntegerField(),
        ),
    ]
