# Generated by Django 5.1.5 on 2025-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0002_alter_customuser_address_alter_customuser_cnicno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
