# Generated by Django 5.1.5 on 2025-01-21 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
