# Generated by Django 5.1.5 on 2025-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0005_user_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='abutt042', max_length=150, unique=True),
        ),
    ]
