# Generated by Django 5.1.5 on 2025-02-13 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
