# Generated by Django 5.1.5 on 2025-01-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0010_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
