# Generated by Django 5.1.5 on 2025-01-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0013_alter_attendance_user_alter_expense_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Other', 'Other')], max_length=100)),
                ('leave_date', models.DateField()),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('reason', models.TextField()),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_time', models.TimeField(blank=True, null=True)),
                ('leave_days', models.IntegerField(default=0)),
                ('leave_balance', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='ufcmsdb.user')),
            ],
        ),
    ]
