# Generated by Django 5.1.5 on 2025-01-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0014_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_date',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half-day', 'Half-day')], max_length=10),
        ),
    ]
