# Generated by Django 5.1.5 on 2025-01-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0015_remove_leave_leave_date_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_leave_balance',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='yearly_leave_balance',
            field=models.IntegerField(default=24),
        ),
    ]
