# Generated by Django 5.1.5 on 2025-01-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufcmsdb', '0016_user_monthly_leave_balance_user_yearly_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Other', 'Other')], max_length=100),
        ),
    ]
